.TH "BOSCO\-AUDIT" "3" "March 2015" "" ""
.SH "NAME"
\fBbosco-audit\fR \- Run 'bosco audit' across all repositories in your Github team\.
.SH SYNOPSIS
.P
.RS 2
.nf
bosco audit
bosco audit \-r <repoPattern>
.fi
.RE
.SH DESCRIPTION
.P
This command is used to audit every node\.js project in bosco\. Bosco auditi
currently uses the node security projects module \fBnsp\fR to check against a list
of known vulnrabilities\.
.SH COMMAND LINE OPTIONS
.SS \-r, \-\-repo
.RS 0
.IP \(bu 2
Default: \.*
.IP \(bu 2
Type: String

.RE
.P
This sets a regex string to use to filter the repostory list\.
