.TH "BOSCO\-PULL" "3" "September 2014" "" ""
.SH "NAME"
\fBbosco-pull\fR \- Run 'git pull \-\-rebase master' across all repositories in your Github team\.
.SH SYNOPSIS
.P
.RS 2
.nf
bosco pull
.fi
.RE
.SH DESCRIPTION
.P
This command is used to pull changes from all of the github repositories in your configured Github team\.
.P
It is called as part of the wrapper script: \fBmorning\fR\|\.
.SH SEE ALSO
.RS 0
.IP \(bu 2
bosco help morning

.RE
