#!/bin/bash

# This code was borrowed from the Grunt project:
#
# Copyright (c) 2014 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable bash <tab> completion for bosco, add the following line (minus the
# leading #, which is the bash comment character) to your ~/.bashrc file:
#
# eval "$(bosco --completion=bash)"


# Enable bash autocompletion.
function _bosco_completions() {
  # The currently-being-completed word.
  local cur="${COMP_WORDS[COMP_CWORD]}"
  # The current grunt version, available tasks, options, etc.
  local boscoinfo="$(bosco --shellCommands 2>/dev/null)"
  # Options and tasks.
  local compls="$(echo "$boscoinfo" | awk '/Available commands: / {$1=$2=""; print $0}')"
  local opts="$(echo "$boscoinfo" | awk '/Available options: / {$1=$2=""; print $0}')"
  # Only add -- or - options if the user has started typing -
  [[ "$cur" == -* ]] && compls="$compls $opts"
  # Tell complete what stuff to show.
  COMPREPLY=($(compgen -W "$compls" -- "$cur"))
}

complete -o default -F _bosco_completions bosco